### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


In [1]:
import numpy as np

In [23]:
vector = np.random.rand(10)
print(f"Вектор \n{vector}")
print(f"розмірності {vector.shape}")

Вектор 
[0.08278654 0.45101412 0.98186819 0.43615808 0.20646746 0.46672753
 0.61571895 0.54764673 0.41603629 0.2571498 ]
розмірності (10,)


In [24]:
matrix = np.array([[11, 14, 17],
                   [20, 23, 26],
                   [29, 32, 35]])
print(f"Матриця \n{matrix}")
print(f"розмірності {matrix.shape}")

Матриця 
[[11 14 17]
 [20 23 26]
 [29 32 35]]
розмірності (3, 3)



### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


In [25]:
np.round(vector+10, 2)

array([10.08, 10.45, 10.98, 10.44, 10.21, 10.47, 10.62, 10.55, 10.42,
       10.26])

In [26]:
matrix*2

array([[22, 28, 34],
       [40, 46, 52],
       [58, 64, 70]])

In [29]:
square_vector = np.square(vector)
square_vector

array([0.00685361, 0.20341374, 0.96406515, 0.19023387, 0.04262881,
       0.21783459, 0.37910982, 0.29991694, 0.17308619, 0.06612602])


### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [30]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)

array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

In [32]:
# множення матриць А та B, щоб отримати матрицю 2x2
result_matrix = np.dot(B, A)
result_matrix, result_matrix.shape

(array([[0.7281, 0.5202],
        [0.2034, 0.2846]]),
 (2, 2))

In [35]:
# множення result_matrix на вектор C
result_vector = np.dot(result_matrix, C)
result_vector, result_vector.shape

(array([[0.5202],
        [0.2846]]),
 (2, 1))

In [38]:
# множення result_matrix на матрицю D
mult_matrix = np.dot(result_matrix, D)
mult_matrix, mult_matrix.shape

(array([[0.5202, 0.7281],
        [0.2846, 0.2034]]),
 (2, 2))


### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




In [43]:
result_matrix_T = result_matrix.T
print(f"Транспонована матриця: \n{result_matrix_T}")

Транспонована матриця: 
[[0.7281 0.2034]
 [0.5202 0.2846]]


In [49]:
print(f"Вектор \n{vector} до траспонування має розмірність {vector.shape}")
print(f"Вектор після траспонування має розмірність {vector.T.shape}")

Вектор 
[0.08278654 0.45101412 0.98186819 0.43615808 0.20646746 0.46672753
 0.61571895 0.54764673 0.41603629 0.2571498 ] до траспонування має розмірність (10,)
Вектор після траспонування має розмірність (10,)


**Спостереження:** 
Не бачу зміни структури при транспонуванні вектора.

In [53]:
column_vector = np.expand_dims(vector, axis=1)
column_vector, column_vector.shape

(array([[0.08278654],
        [0.45101412],
        [0.98186819],
        [0.43615808],
        [0.20646746],
        [0.46672753],
        [0.61571895],
        [0.54764673],
        [0.41603629],
        [0.2571498 ]]),
 (10, 1))

**Спостереження:**
Вектор-рядок став вектором-стовпцем.

In [57]:
column_vector_t = column_vector.T
column_vector_t, column_vector_t.shape

(array([[0.08278654, 0.45101412, 0.98186819, 0.43615808, 0.20646746,
         0.46672753, 0.61571895, 0.54764673, 0.41603629, 0.2571498 ]]),
 (1, 10))