**1. Створення масивів**

Створіть (кожен пункт оцінюється в 0.5 бала):
- Масив зі списку `[5, 15, 25, 35, 45]`
- Масив з нулів розміром 7
- Масив з одиниць розміром 6
- Масив з числами від 10 до 19 використовуючи `np.arange()`

In [2]:
import numpy as np

In [15]:
arr = np.array([5, 15, 25, 35, 45])
display(arr)

zeros = np.zeros(7)
display(zeros)

ones = np.ones(6)
display(ones)

range_arr = np.arange(10, 20)
display(range_arr)

array([ 5, 15, 25, 35, 45])

array([0., 0., 0., 0., 0., 0., 0.])

array([1., 1., 1., 1., 1., 1.])

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])


---

**2. Базові операції**

Створіть Numpy-масив зі значеннями [12, 24, 36, 48, 60].

Виконайте наступні операції над **оригінальним** масивом і запишіть у нову змінну результат (кожен пункт оцінюється в 0.5 бала):
- Помножте всі елементи на 2
- Додайте до всіх елементів 10
- Піднесіть всі елементи до квадрату
- Обчисліть квадратний корінь з усіх елементів

Виведіть результат виконання кожної операції.

In [23]:
arr = np.array([12, 24, 36, 48, 60])
print(f"Оригінальний масив: {arr}")
print(f"Результат множення на 2: {arr * 2}")
print(f"Результат додавання 10: {arr + 10}")
print(f"Результат піднесення до квадрата: {arr ** 2}")
print(f"Результат взяття квадратного кореня: {np.sqrt(arr)}")


Оригінальний масив: [12 24 36 48 60]
Результат множення на 2: [ 24  48  72  96 120]
Результат додавання 10: [22 34 46 58 70]
Результат піднесення до квадрата: [ 144  576 1296 2304 3600]
Результат взяття квадратного кореня: [3.46410162 4.89897949 6.         6.92820323 7.74596669]



---

**3. Статистичні функції**

Створіть Numpy-масив `data` зі значеннями [18, 27, 33, 41, 52, 68, 79].

Обчисліть використовуючи функціонал numpy (кожен пункт оцінюється в 0.5 бала):
- Середнє значення
- Мінімум
- Максимум
- Суму всіх елементів

In [33]:
data = np.array([18, 27, 33, 41, 52, 68, 79])
print(f"Поточний масив {data}")
mean = np.mean(data)
print(F"Середнє значення = {mean}")
minimum = np.min(data)
print(F"Мінімальне значення = {minimum}")
maximum = np.max(data)
print(F"Мінімальне значення = {maximum}")
total = np.sum(data)
print(f"Сума всіх елементів = {total}")

Поточний масив [18 27 33 41 52 68 79]
Середнє значення = 45.42857142857143
Мінімальне значення = 18
Мінімальне значення = 79
Сума всіх елементів = 318



---

**4. Індексація**

Створіть Numpy-масив `arr` зі значеннями [15, 22, 35, 44, 58, 67].

Виведіть (кожен пункт оцінюється в 0.5 бала):
- Перший елемент
- Останній елемент
- Елементи з індексами 1 до 3
- Елементи більші за 40

In [40]:
arr = np.array([15, 22, 35, 44, 58, 67])
print(f"Дано масив: {arr}")
print(f"Перший елемент: {arr[0]}")
print(f"Останній елемент: {arr[-1]}")
print(f"Елементи з індексами 1 до 3 (включно): {arr[1:4]}")
print(f"Елементи більші за 40: {arr[arr>40]}")

Дано масив [15 22 35 44 58 67]
Перший елемент: 15
Останній елемент: 67
Елементи з індексами 1 до 3 (включно): [22 35 44]
Елементи більші за 40: [44 58 67]



---


**5. Двовимірні масиви**

Задано матрицю 3x3.

Виконайте наступні дії з функціоналом Numpy (кожен пункт оцінюється в 0.5 бала):
- Виведіть форму (shape) матриці
- Виведіть перший рядок
- Виведіть другу колонку
- Обчисліть суму всіх елементів
- Обчисліть середнє всіх елементів

In [41]:
matrix = np.array([[2, 4, 6],
                   [8, 10, 12],
                   [14, 16, 18]])

In [53]:
display(matrix)
print(f"Форма матриці: {matrix.shape}")
print(f"Перший рядок: {matrix[0,:]}")
print(f"Друга колонка: {matrix[:,1]}")
print(f"Суму всіх елементів: {np.sum(matrix)}")
print(f"Середнє всіх елементів: {np.mean(matrix)}")

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

Форма матриці: (3, 3)
Перший рядок: [2 4 6]
Друга колонка: [ 4 10 16]
Суму всіх елементів: 90
Середнє всіх елементів: 10.0
